import {Header} from './header';
import {Footer} from './footer';
import { font_opensans } from './_utils/font';

import './global.css';



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={font_opensans.className}>
        <Header />
          {children}
	      <Footer />
      </body>
    </html>
  );
}
